# Generated by Django 4.2.7 on 2023-11-08 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_mnemonic_account_seed_phrase"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="id",
        ),
        migrations.AlterField(
            model_name="account",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="account",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
