# Generated by Django 4.2.7 on 2023-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trait",
            name="type",
            field=models.CharField(
                choices=[("s", "String"), ("n", "Number")], default="s", max_length=64
            ),
        ),
    ]
