# Generated by Django 4.2.7 on 2023-11-07 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="properties",
            name="traits",
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("value", models.CharField(max_length=64)),
                (
                    "type",
                    models.CharField(
                        choices=[("s", "String"), ("n", "Number")],
                        default="s",
                        max_length=64,
                    ),
                ),
                (
                    "Properties",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nfts.properties",
                    ),
                ),
            ],
        ),
    ]
