# Generated by Django 4.2.7 on 2023-11-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0002_remove_properties_traits_trait"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trait",
            old_name="Properties",
            new_name="properties",
        ),
        migrations.AlterField(
            model_name="nft",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="nft",
            name="image_integrity",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="trait",
            name="type",
            field=models.CharField(
                choices=[("s", "String"), ("n", "Number")], default="s", max_length=64
            ),
        ),
    ]
