# Generated by Django 4.2.7 on 2023-11-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0002_alter_trait_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="traits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.DeleteModel(
            name="Trait",
        ),
    ]
