# Generated by Django 4.2.7 on 2023-11-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0003_properties_traits_delete_trait"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="clawback",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="nft",
            name="freeze",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="nft",
            name="mananger",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="nft",
            name="reserve",
            field=models.CharField(blank=True, default="", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="properties",
            name="traits",
            field=models.JSONField(default=dict),
        ),
    ]
