# Generated by Django 4.2.7 on 2023-11-09 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0004_alter_nft_clawback_alter_nft_freeze_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nft",
            old_name="mananger",
            new_name="manager",
        ),
    ]
