# Generated by Django 4.2.7 on 2023-11-09 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0005_rename_mananger_nft_manager"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nft",
            old_name="owner",
            new_name="creator",
        ),
    ]
