# Generated by Django 4.2.7 on 2023-11-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0005_alter_trait_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nft",
            name="image",
            field=models.ImageField(upload_to="nfts/images"),
        ),
        migrations.AlterField(
            model_name="trait",
            name="type",
            field=models.CharField(
                choices=[("s", "String"), ("n", "Number")], default="s", max_length=64
            ),
        ),
    ]
