# Generated by Django 4.2.7 on 2023-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0006_rename_owner_nft_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="is_claimable",
            field=models.BooleanField(default=False),
        ),
    ]
