# Generated by Django 4.2.7 on 2023-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0006_alter_nft_image_alter_trait_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="index",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="trait",
            name="type",
            field=models.CharField(
                choices=[("s", "String"), ("n", "Number")], default="s", max_length=64
            ),
        ),
    ]
