# Generated by Django 4.2.7 on 2023-11-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nfts", "0009_alter_trait_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="nft",
            name="clawback",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nft",
            name="decimals",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nft",
            name="freeze",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nft",
            name="mananger",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nft",
            name="reserve",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="nft",
            name="total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="nft",
            name="unit",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trait",
            name="type",
            field=models.CharField(
                choices=[("s", "String"), ("n", "Number")], default="s", max_length=64
            ),
        ),
    ]
